version: '3.3'

services:
  web:
    build: .
    command: sh -c "rm -f logs/logs.log && gunicorn --workers 4 --limit-request-line 0 --timeout 0 --bind 0.0.0.0:8157 --preload app:app"
    volumes:
      - .:/app
    ports:
      - 8157:8157
   